batch_size: 64
dataset_path: data/data_full
height: 32
learning_rate: 0.005
max_text_length: 7
model_path: models/handwriting_recognition_torch/202412070826
train_epochs: 100
vocab: '#+-12345678=BKNOQRabcdefghx'
width: 128
